#ifndef DOCTYPE_H
#define DOCTYPE_H

#define DOCTYPE_NEWTICKET 1
#define DOCTYPE_PASSTICKET 2
#define DOCTYPE_USEDTICKET 3
#define DOCTYPE_BACKTICKET 4
#define DOCTYPE_TRASHTICKET 5
#define DOCTYPE_DEBTPAY 6
#define DOCTYPE_STORERESET 7
#define DOCTYPE_FLASHSALE 8

#endif // DOCTYPE_H
